// apps/extension/components/WhisperingButton.tsx
import { Button, type ButtonProps } from '@/components/ui/button';
import {
	Tooltip,
	TooltipContent,
	TooltipProvider,
	TooltipTrigger,
} from '@/components/ui/tooltip';
import type { PropsWithChildren, ReactNode } from 'react';

export function WhisperingButton({
	children,
	tooltipContent,
	...restProps
}: PropsWithChildren<{ tooltipContent: ReactNode } & ButtonProps>) {
	return (
		<TooltipProvider>
			<Tooltip>
				<TooltipTrigger asChild>
					<Button {...restProps}>
						{children}
						<span className="sr-only">{tooltipContent}</span>
					</Button>
				</TooltipTrigger>
				<TooltipContent>{tooltipContent}</TooltipContent>
			</Tooltip>
		</TooltipProvider>
	);
}

// apps/app/src/lib/components/WhisperingButton.svelte
<script lang="ts">
import { Button, type Props } from '$lib/components/ui/button';
import * as Tooltip from '$lib/components/ui/tooltip';

let {
	children,
	tooltipText,
	...restProps
}: {
	tooltipText: string;
} & Props = $props();
</script>

<Tooltip.Root>
	<Tooltip.Trigger asChild let:builder>
		<Button builders={[builder]} {...restProps}>
			{#if children}
				{@render children()}
			{/if}
			<span class="sr-only">{tooltipText}</span>
		</Button>
	</Tooltip.Trigger>
	<Tooltip.Content>
		<p>{tooltipText}</p>
	</Tooltip.Content>
</Tooltip.Root>
